name: NodeJS with CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./assets

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      working-directory: ./assets

    - name: Build
      run: npm run build
      working-directory: ./assets